// apps/web/src/lib/components/atoms/Badge.svelte
<script lang="ts">
  let {
    label,
    bg = '#EBF6FD',
    color = '#045098'
  }: { label: string; bg?: string; color?: string } = $props();
</script>

<span class="inline-flex items-center rounded-full px-2.5 py-1" style={`background:${bg}; color:${color}; font-size:12px; font-weight:800; letter-spacing:0.03em`}>
  {label}
</span>

// legacy/src/app/components/atoms/Badge.tsx
import React from "react";

interface BadgeProps {
  label: string;
  bg: string;
  color: string;
}

export function Badge({ label, bg, color }: BadgeProps) {
  return (
    <span
      className="inline-flex items-center px-2.5 py-1 rounded-full"
      style={{
        backgroundColor: bg,
        color: color,
        fontSize: "11px",
        fontWeight: 700,
        letterSpacing: "0.08em",
        textTransform: "uppercase" as const,
        lineHeight: 1.2,
      }}
    >
      {label}
    </span>
  );
}
