// legacy/src/app/components/atoms/Tag.tsx
import React from "react";

interface TagProps {
  label: string;
  active?: boolean;
  onClick?: () => void;
}

export function Tag({ label, active = false, onClick }: TagProps) {
  return (
    <button
      onClick={onClick}
      className="inline-flex items-center px-4 py-2 rounded-full cursor-pointer transition-all duration-200 whitespace-nowrap"
      style={{
        backgroundColor: active ? "#1387C7" : "#EEF2FB",
        color: active ? "#FFFFFF" : "#4A5068",
        fontWeight: 600,
        fontSize: "14px",
        border: "none",
      }}
    >
      {label}
    </button>
  );
}

// apps/web/src/lib/components/atoms/Tag.svelte
<script lang="ts">
  let {
    label,
    active = false,
    onclick
  }: { label: string; active?: boolean; onclick?: () => void } = $props();
</script>

<button
  {onclick}
  class="inline-flex cursor-pointer items-center whitespace-nowrap rounded-full px-4 py-2 transition-all duration-200"
  style={`background:${active ? '#1387C7' : '#EEF2FB'}; color:${active ? '#fff' : '#4A5068'}; font-weight:600; font-size:14px; border:none`}
>
  {label}
</button>
