// apps/web/src/lib/components/layout/BottomNavBar.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import { MapPin, MessageCircle } from '@lucide/svelte';
  import WhatsAppIcon from '$lib/components/icons/WhatsAppIcon.svelte';
  import { chatbot } from '$lib/stores/chatbot.svelte';

  const WA_LINK = 'https://wa.me/528002905050?text=Quiero%20recibir%20las%20promos%20de%20Kiosko';

  let pressedId = $state<string | null>(null);

  // Prueba A/B: nombre singular de la sección de tiendas.
  const locSingular = $derived(($page.data.locationsLabelSingular as string) ?? 'Sucursal');

  const items = $derived([
    { id: 'sucursal', label: locSingular, bg: '#1387C7', action: () => goto('/sucursales') },
    { id: 'whatsapp', label: 'WhatsApp', bg: '#25D366', action: () => window.open(WA_LINK, '_blank', 'noopener,noreferrer') },
    { id: 'soporte', label: 'Soporte', bg: '#045098', action: () => chatbot.open() }
  ]);
</script>

<nav class="fixed z-50 md:hidden" style="bottom:16px; left:16px; right:16px; background:rgba(255,255,255,0.66); border-radius:16px; box-shadow:0 4px 30px rgba(0,0,0,0.1); backdrop-filter:blur(20px); -webkit-backdrop-filter:blur(20px); padding:10px 16px">
  <div class="flex items-center justify-around">
    {#each items as item (item.id)}
      <button
        onclick={item.action}
        ontouchstart={() => (pressedId = item.id)}
        ontouchend={() => (pressedId = null)}
        onmousedown={() => (pressedId = item.id)}
        onmouseup={() => (pressedId = null)}
        onmouseleave={() => (pressedId = null)}
        class="flex cursor-pointer items-center justify-center"
        style={`background:none; border:none; padding:0; transform:scale(${pressedId === item.id ? 1.1 : 1}); transition:transform 150ms ease`}
        aria-label={item.label}
      >
        <div class="flex items-center justify-center rounded-full" style={`width:44px; height:44px; background:${item.bg}; color:#fff; box-shadow:0 2px 8px ${item.bg}40`}>
          {#if item.id === 'sucursal'}<MapPin style="width:22px; height:22px" />
          {:else if item.id === 'whatsapp'}<WhatsAppIcon size={22} />
          {:else}<MessageCircle style="width:22px; height:22px" />{/if}
        </div>
      </button>
    {/each}
  </div>
</nav>

<!-- Espaciador para que el contenido no quede oculto tras la barra en móvil -->
<div class="md:hidden" style="height:80px"></div>

// legacy/src/app/components/molecules/BottomNavBar.tsx
import React, { useState } from "react";
import { useNavigate, useLocation } from "react-router";
import { MapPin, MessageCircle } from "lucide-react";
import { useChatbot } from "../../context/ChatbotContext";

function WhatsAppIcon({ size = 20 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor">
      <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z" />
    </svg>
  );
}

const WA_LINK =
  "https://wa.me/528002905050?text=Quiero%20recibir%20las%20promos%20de%20Kiosko";

interface ActionItem {
  id: string;
  label: string;
  icon: React.ReactNode;
  bg: string;
  action: () => void;
}

export function BottomNavBar() {
  const navigate = useNavigate();
  const location = useLocation();
  const [pressedId, setPressedId] = useState<string | null>(null);
  const { open: openChatbot } = useChatbot();

  const items: ActionItem[] = [
    {
      id: "sucursal",
      label: "Sucursal",
      icon: <MapPin style={{ width: 22, height: 22 }} />,
      bg: "#1387C7",
      action: () => navigate("/sucursales"),
    },
    {
      id: "whatsapp",
      label: "WhatsApp",
      icon: <WhatsAppIcon size={22} />,
      bg: "#25D366",
      action: () => window.open(WA_LINK, "_blank", "noopener,noreferrer"),
    },
    {
      id: "soporte",
      label: "Soporte",
      icon: <MessageCircle style={{ width: 22, height: 22 }} />,
      bg: "#045098",
      action: () => openChatbot(),
    },
  ];

  // Highlight sucursal when on that route
  const isActive = (id: string) => {
    if (id === "sucursal") return location.pathname.startsWith("/sucursales");
    return false;
  };

  return (
    <>
      <nav
        className="fixed z-50 md:hidden"
        style={{
          bottom: 15,
          left: 15,
          right: 15,
          background: "rgba(255, 255, 255, 0.55)",
          backdropFilter: "blur(20px) saturate(180%)",
          WebkitBackdropFilter: "blur(20px) saturate(180%)",
          border: "1px solid rgba(255, 255, 255, 0.6)",
          borderRadius: 24,
          boxShadow:
            "0 8px 32px rgba(0, 0, 0, 0.10), 0 2px 8px rgba(0,0,0,0.06)",
          padding: "10px 12px",
        }}
      >
        <div className="flex items-center justify-around">
          {items.map((item) => {
            const pressed = pressedId === item.id;
            return (
              <button
                key={item.id}
                onClick={item.action}
                onTouchStart={() => setPressedId(item.id)}
                onTouchEnd={() => setPressedId(null)}
                onMouseDown={() => setPressedId(item.id)}
                onMouseUp={() => setPressedId(null)}
                onMouseLeave={() => setPressedId(null)}
                className="flex items-center justify-center cursor-pointer"
                style={{
                  background: "none",
                  border: "none",
                  padding: 0,
                  transform: pressed ? "scale(1.1)" : "scale(1)",
                  transition: "transform 150ms ease",
                }}
                aria-label={item.label}
              >
                <div
                  className="flex items-center justify-center rounded-full"
                  style={{
                    width: 44,
                    height: 44,
                    backgroundColor: item.bg,
                    color: "#FFFFFF",
                    boxShadow: `0 2px 8px ${item.bg}40`,
                  }}
                >
                  {item.icon}
                </div>
              </button>
            );
          })}
        </div>
      </nav>

      {/* Spacer to prevent content from being hidden behind nav bar on mobile */}
      <div className="md:hidden" style={{ height: 75 }} />
    </>
  );
}
