// apps/web/src/lib/components/molecules/WhatsAppNewsletterWidget.svelte
<script lang="ts">
  import WhatsAppIcon from '$lib/components/icons/WhatsAppIcon.svelte';

  const waLink = 'https://wa.me/528002905050?text=Hola%2C%20quiero%20unirme%20al%20grupo%20de%20promociones%20de%20Kiosko';
</script>

<div class="flex flex-col items-center gap-4 px-6 py-6 sm:flex-row sm:gap-6 sm:py-5" style="background:#F0F9EC; border:1.5px solid #D4EDCA; border-radius:16px">
  <div class="flex flex-shrink-0 items-center gap-3">
    <div class="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full" style="background:#25D366">
      <WhatsAppIcon size={24} class="text-white" />
    </div>
  </div>

  <div class="flex flex-1 flex-col gap-1 text-center sm:text-left">
    <span style="font-size:16px; font-weight:700; color:#1A1D2E; line-height:1.3">¿Quieres las promos antes que nadie?</span>
    <span style="font-size:14px; color:#4A5068">Únete a nuestro grupo de difusión en WhatsApp</span>
  </div>

  <a href={waLink} target="_blank" rel="noopener noreferrer" class="inline-flex w-full flex-shrink-0 items-center justify-center gap-2 px-6 py-3 no-underline transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg sm:w-auto" style="background:#25D366; color:#fff; font-size:14px; font-weight:700; border-radius:16px">
    <WhatsAppIcon size={16} class="text-white" />
    Unirme al grupo
  </a>
</div>

// legacy/src/app/components/molecules/WhatsAppNewsletterWidget.tsx
import React from "react";

function WhatsAppIcon({ className, style }: { className?: string; style?: React.CSSProperties }) {
  return (
    <svg className={className} style={style} viewBox="0 0 24 24" fill="currentColor">
      <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z" />
    </svg>
  );
}

export function WhatsAppNewsletterWidget() {
  const waLink =
    "https://wa.me/528002905050?text=Hola%2C%20quiero%20unirme%20al%20grupo%20de%20promociones%20de%20Kiosko";

  return (
    <div
      className="flex flex-col sm:flex-row items-center gap-4 sm:gap-6 px-6 py-6 sm:py-5"
      style={{
        backgroundColor: "#F0F9EC",
        border: "1.5px solid #D4EDCA",
        borderRadius: "16px",
      }}
    >
      <div className="flex items-center gap-3 flex-shrink-0">
        <div
          className="w-12 h-12 rounded-full flex items-center justify-center flex-shrink-0"
          style={{ backgroundColor: "#25D366" }}
        >
          <WhatsAppIcon className="w-6 h-6" style={{ color: "#FFFFFF" }} />
        </div>
      </div>

      <div className="flex flex-col gap-1 flex-1 text-center sm:text-left">
        <span
          style={{
            fontSize: "16px",
            fontWeight: 700,
            color: "#1A1D2E",
            lineHeight: 1.3,
          }}
        >
          ¿Quieres las promos antes que nadie?
        </span>
        <span style={{ fontSize: "14px", color: "#4A5068" }}>
          Únete a nuestro grupo de difusión en WhatsApp
        </span>
      </div>

      <a
        href={waLink}
        target="_blank"
        rel="noopener noreferrer"
        className="no-underline inline-flex items-center gap-2 px-6 py-3 transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg flex-shrink-0"
        style={{
          backgroundColor: "#25D366",
          color: "#FFFFFF",
          fontSize: "14px",
          fontWeight: 700,
          borderRadius: "16px",
        }}
      >
        <WhatsAppIcon className="w-4 h-4" style={{ color: "#FFFFFF" }} />
        Unirme al grupo
      </a>
    </div>
  );
}
